// Generated by CoffeeScript 1.6.3
(function() {
  var app, async, pushState;

  app = require('express.io')();

  async = require('async');

  app.http().io();

  pushState = function() {};

  app.io.on('connection', function(socket) {
    return console.log('New socket connection!');
  });

  app.io.route('joinRoom', function(req) {
    pushState();
    console.log('Request to join room: ' + req.data.room);
    return req.socket.get('currentRoom', function(err, currentRoom) {
      if (currentRoom) {
        req.io.leave(currentRoom);
        app.io.room(currentRoom).broadcast('event', {
          type: 'meta',
          text: 'OMG someone left the room: ' + currentRoom
        });
      }
      return req.socket.set('currentRoom', req.data.room, function(err) {
        req.io.join(req.data.room);
        return app.io.room(req.data.room).broadcast('event', {
          type: 'meta',
          text: 'OMG someone joined the room: ' + req.data.room
        });
      });
    });
  });

  app.io.route('sendMessage', function(req) {
    return req.socket.get('currentRoom', function(err, currentRoom) {
      console.log(currentRoom);
      return app.io.room(currentRoom).broadcast('event', {
        type: 'message',
        text: req.data
      });
    });
  });

  app.io.route('setName', function(req) {
    return console.log('Request to change name!');
  });

  app.listen(7076);

}).call(this);
