// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('realtimesteezApp').directive('message', function(socket) {
    return {
      templateUrl: 'views/message.html',
      restrict: 'E',
      link: function(scope, element, attrs) {
        return scope.sendMessage = function() {
          if (scope.data.message) {
            socket.emit('sendMessage', scope.data.message);
            return scope.data.message = '';
          }
        };
      }
    };
  });

}).call(this);
