// Generated by CoffeeScript 1.6.3
(function() {
  var get, q, set;

  q = require('q');

  get = function(socket, param) {
    var deferred;
    deferred = q.defer();
    socket.get(param, function(err, data) {
      if (err) {
        return deferred.reject(new Error(error));
      } else {
        return deferred.resolve(data);
      }
    });
    return deferred.promise;
  };

  set = function(socket, param, value) {
    var deferred;
    deferred = q.defer();
    socket.set(param, value, function(err) {
      if (err) {
        return deferred.reject(new Error(error));
      } else {
        console.log('done!');
        return deferred.resolve(value);
      }
    });
    return deferred.promise;
  };

  module.exports = {
    get: get,
    set: set
  };

}).call(this);
