// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Directive: message', function() {
    var element;
    beforeEach(module('realtimesteezApp'));
    element = {};
    return it('should make hidden element visible', inject(function($rootScope, $compile) {
      element = angular.element('<message></message>');
      element = $compile(element)($rootScope);
      return expect(element.text()).toBe('this is the message directive');
    }));
  });

}).call(this);
