// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('realtimesteezApp').controller('MainCtrl', function($scope, $routeParams, socket) {
    var room;
    console.log($routeParams.room);
    $scope.data = {
      events: [],
      name: localStorage.name
    };
    socket.on('event', function(res) {
      return $scope.data.events.push(res);
    });
    room = $routeParams.room;
    if (room) {
      console.log('joining room: ' + room);
      socket.emit('joinRoom', {
        room: room,
        name: $scope.data.name
      });
    }
    return $scope.changeName = function() {
      console.log($scope.data.name);
      if ($scope.data.name) {
        socket.emit('changeName', $scope.data.name);
        return localStorage.name = $scope.data.name;
      }
    };
  });

}).call(this);
