// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('realtimesteezApp').controller('MainCtrl', function($scope, $routeParams, socket) {
    var room;
    console.log($routeParams.room);
    $scope.data = {
      events: [],
      name: 'Alonso'
    };
    socket.on('event', function(res) {
      return $scope.data.events.push(res);
    });
    room = $routeParams.room;
    if (room) {
      console.log('joining room: ' + room);
      socket.emit('joinRoom', {
        room: room
      });
    }
    return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
  });

}).call(this);
