// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('realtimesteezApp', []).config(function($routeProvider) {
    return $routeProvider.when('/:room', {
      templateUrl: 'views/main.html',
      controller: 'MainCtrl'
    }).otherwise({
      redirectTo: '/'
    });
  });

}).call(this);
