// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Service: socket', function() {
    var socket;
    beforeEach(module('realtimesteezApp'));
    socket = {};
    beforeEach(inject(function(_socket_) {
      return socket = _socket_;
    }));
    return it('should do something', function() {
      return expect(!!socket).toBe(true);
    });
  });

}).call(this);
