// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('realtimesteezApp').factory('socket', function($rootScope) {
    var socket;
    socket = io.connect('http://localhost:7076');
    return {
      on: function(eventName, callback) {
        return socket.on(eventName, function(data) {
          var args;
          console.log(data);
          args = arguments;
          return $rootScope.$apply(function() {
            return callback.apply(socket, args);
          });
        });
      },
      emit: function(eventName, data, callback) {
        console.log('emitting: ' + eventName);
        return socket.emit(eventName, data, function() {
          var args;
          console.log(arguments);
          args = arguments;
          return $rootScope.$apply(function() {
            if (callback) {
              return callback.apply(socket, args);
            }
          });
        });
      }
    };
  });

}).call(this);
